name: Node Based Application Deployment

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Configure AWS CLI
        run: |
          mkdir -p ~/.aws
          echo "[default]" > ~/.aws/config
          echo "region = ${{ secrets.AWS_DEFAULT_REGION }}" >> ~/.aws/config
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials

      - name: Download .env from S3
        run: |
          aws s3 cp "${{ secrets.BUCKET }}"/.env .env

      # - name: Install dependencies
      #   run: |
      #     npm install

      - name: Stop PM2 process
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no -T -p "${{ secrets.HOST_PORT }}" "${{ secrets.SSH_USERNAME }}"@"${{ secrets.HOST_IP }}" "
            source ~/.nvm/nvm.sh && pm2 stop 0
          "
      
      - name: Deploy application
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" scp -r -P "${{ secrets.HOST_PORT }}" * "${{ secrets.SSH_USERNAME }}"@"${{ secrets.HOST_IP }}":/home/ubuntu/signup/

      # - name: Start PM2 process
      #   run: |
      #     sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no -T -p "${{ secrets.HOST_PORT }}" "${{ secrets.SSH_USERNAME }}"@"${{ secrets.HOST_IP }}" "
      #       source ~/.nvm/nvm.sh && pm2 restart 0 --update-env
      #     "
